### ISSUE TITLE
Add -? as a flag for help

### ISSUE THREAD

**Issue by burhan** [cli-guidelines/cli-guidelines#121]
`-?` is a [common flag for help](https://www.ibm.com/docs/en/ds8870/7.4?topic=commands-common-command-flags)

**Comment by thiagola92** [comment]
I never saw `-?` for help, it's really common?

**Comment by wookietreiber** [comment]
> I never saw `-?` for help, it's really common?

Not that I'm a huge maintainer/contributor in CLI apps :sweat_smile: but I have some out there and I'm using `-?` over `-h` in all my tools, right from the get-go. `?` clearly indicates a question / asking for help, while, situational, `-h` might be a more suitable abbreviation for something else, most notably in network-related tools for `--host`.

**Comment by aanand** [comment]
Not weighing in on the `-?` question (which I don't have a strong opinion about), I just want to address this:

> `-h` might be a more suitable abbreviation for something else, most notably in network-related tools for `--host`. In case I later figure out that I'd need `-h` for something else, I'd need to deprecate it first or do a hard switch with the CLI or that I'd have to use a less appropriate short version

It's ultimately up to you, but the guidelines directly advise against this in a couple of places ("Don't overload `-h`"; "`-h`... should only mean help"). Users of your tools will expect `-h` to mean "help", because it's a de facto standard. I've tripped up on `docker run -h` many times for this exact reason.

**Comment by wookietreiber** [comment]
> Not weighing in on the `-?` question (which I don't have a strong opinion about), I just want to address this:
> 
> > `-h` might be a more suitable abbreviation for something else, most notably in network-related tools for `--host`. In case I later figure out that I'd need `-h` for something else, I'd need to deprecate it first or do a hard switch with the CLI or that I'd have to use a less appropriate short version
> 
> It's ultimately up to you, but the guidelines directly advise against this in a couple of places ("Don't overload `-h`"; "`-h`... should only mean help"). Users of your tools will expect `-h` to mean "help", because it's a de facto standard. I've tripped up on `docker run -h` many times for this exact reason.

whoopsie :sweat_smile:

**Comment by burhan** [comment]
There are some other considerations, and there isn't a defined standard, but lots of guidelines:

- the [GNU Coding Standard](https://www.gnu.org/prep/standards/standards.html#g_t_002d_002dhelp) mentions `--help` .

- there is nothing in the [POSIX Utility conventions](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) for this.

- the [bash programming guide](https://tldp.org/LDP/abs/html/standard-options.html) mention `-h` (and `--help`)

- the [Microsoft Command Line Standard](https://devblogs.microsoft.com/powershell/microsoft-command-line-standard/) mentions that _Commands must support `-?`, `–Help`, `-Version`, `–Verbose`, and `–Debug` for all commands_

The [documentation for `getopt()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getopt.html) states 

>If getopt() encounters an option character that is not contained in optstring, it shall return the <question-mark> ( '?' ) character. If it detects a missing option-argument, it shall return the <colon> character ( ':' ) if the first character of optstring was a <colon>, or a <question-mark> character ( '?' ) otherwise.

I'm assuming this is where this de-facto standard came in. As `?` is returned by `getopt()` for unrecognized options, `-?` became a way to list all options, rather than failing silently. It is unlikely that `-?` would be a common option, unlike `-h` which could mean an actual option. The most common one I know is  [`-h` for `--human-readable` for ls](https://man7.org/linux/man-pages/man1/ls.1.html).

**Comment by eqn-group** [comment]
this is bullshit. only follow posix/gnu standard please.

**Comment by tashian** [comment]
Hey @burhan, thanks for doing some research on this for us!

I have a pretty strong point of view about this.

With CLI Guidlines, we are asking the question:
If you are building a new tool today, from scratch, what should you do?

And, I do not think `-?` should be implemented as a help flag for new CLI apps today.
I think we should stick to the GNU standard here: `--help` is ideal.

However, if an unknown flag is passed in, help should be displayed.
Practically speaking, this will mean that `-?` displays help.
But, we should not explicitly recommend `-?` as a help flag.

### Some background

I think the reason we have `--help` is because `-h` has been overloaded, so `--help` (or `help`) is more reliable.
Unfortunately, `ls` can't change how `-h` behaves. It is set in stone at this point.
The fact that older tools—and even `docker`—have overloaded `-h` is annoying in the same way we have strange exceptions to grammar rules in English.

Meanwhile, there's `-?`.
I think of `-?` as a legacy flag that should not be introduced in new applications.
Applications that initially used `-?` or `-h` have had to later adopt `--help`, but not vice versa.

I think the [MS standard](https://devblogs.microsoft.com/powershell/microsoft-command-line-standard/) that mentions `-?` is tailored to PowerShell programs, and isn't relevant here. PowerShell/Windows has a lot of different conventions from UNIX and is beyond the scope of CLI Guidelines.

When I was poking around for examples just now, I noticed that the `fish` shell treats `-?` as a wildcard:

```
fish$ zip -?
fish: No matches for wildcard '-?'. See `help wildcards-globbing`.
zip -?
    ^^
```

So, `-?` doesn't even work in `fish`. More evidence, in my view, that the world is moving away from `-?`.
