### ISSUE TITLE
Best way to extend/superset these guidelines?

### ISSUE THREAD

**Issue by zkat** [cli-guidelines/cli-guidelines#64]
Hi! As it turns out, y'all releasing this was super timely, as I was working with some folks at my job on coming up with some CLI guidelines that we could use organizationally and for our public tool. What I'm wondering is more your thoughts on how you imagine people extending or building on top of these:

* Is the preferred model "centralize everything, send us PRs for what you want to modify so we can all share a single standard, and don't have your own guidelines on top of this"?
* Is the right way to do this to *fork* your guidelines, keeping all the appropriate attribution of course, but changing styles/name/etc?
* Is it better to just _link back_ to your guidelines and somehow have a system for saying "they say this, but actually we say this other thing instead"?

I'd love to hear about what y'all think. This is a fantastic, amazing document and I definitely think it's the right thing to build anything on top of.

**Comment by bfirsh** [comment]
Thank you so much for your interest!

I will let others chime in, but I think it'd be really nice to centralize it if we can. Firstly because, well, there'll be one thing that we can all point at. But also the process of proposing modifications the guidelines will spark debate, and hopefully help us create better designed guidelines.

So, I'd propose we start trying to do that first. Then, if we come up against any reconcilable differences, then fork away. (Though I hope it won't come to that!)

**Comment by bfirsh** [comment]
Another thought: perhaps there are some things that are specific to your CLI that don't make sense in the CLIG. Perhaps a solution might be something similar to your third suggestion, where your guidelines could be something like "We follow the CLIG for the design of our CLI, with these additional guidelines: ..."

**Comment by aanand** [comment]
Very cool to see this happen!

I agree with Ben - let's see if we can keep it in CLIG for now. Especially in this early stage, there's lots of room to increase the guidelines' clarity and coverage.

**Comment by tashian** [comment]
Hi @zkat, have you [joined our Discord](https://discord.gg/EbAW5rUCkE) yet? We can set up a channel for this if you want to move the discussion over there.

**Comment by zkat** [comment]
Just joined!
