### ISSUE TITLE
Provide a repository with example implementations

### ISSUE THREAD

**Issue by kkirsche** [cli-guidelines/cli-guidelines#74]
This is a fantastic resource, but from what I've found, it's not necessarily easy or straightforward in some languages to implement these solutions. Rather than requiring every developer to re-implement these guidelines from scratch in their language of choice, I would recommend creating a repository of implementations that provide support for this using the language's standard library.

I would recommend using the Builder creational design pattern, as discussed on https://refactoring.guru/design-patterns/builder, to allow developers to control which features they support. I really appreciate the hard work and dedication of the team, and would love to implement these guidelines, but without more concrete resources, I've found at times it's unrealistic. Any solutions, example implementations, etc. would be very useful in my opinion for developers hoping to support this and be a good steward.

**Comment by tashian** [comment]
Thanks Kevin.

Our goal is to provide guidelines that apply broadly, no matter which programming language you're using. That's why we don't offer any code. We do have a few links to libraries we like, for specific languages, that make it easier to implement some of the guidelines. And we welcome contributions to that list.
